tellor-io/dataFeed

- src/utils/helpers.js
Wrongly formatted Rinkeby error crashed the site. The try catch allows this to not bring the whole site down in case another error like this comes through.
> Added 'Try Catch' to Helpers

- src/contexts/Graph.js
added the optimism testnet (kovan) to the Data Feed after deploying the Graph.
> adding optimism kovan

- src/utils/queryDataParsers.js
a fix btc/usd and eth/usd SpotPrice type; showing 0.0 instead of correct price
> btc/eth spot showing 0.0 fix

- src/components/Hero.js
- src/styles/Table.css
Removed "Your Oracle At Work"
added "Recent Reports"
increased header size
standardized table font weight/size
padded tip table margin from feed table
> cosmetic changes

- src/contexts/GraphAutopay.js
- src/utils/helpers.js
- Changed subgraph API links to tellors
> updated api links

- package.json
trying to resolve new error. everything is testing fine locally, hence why im having to keep making new pr's as i troubleshoot.
> lower-casing set

- src/components/Table.js
- src/components/TipTable.js
- src/contexts/Graph.js
- src/utils/chains.js
- src/utils/helpers.js
added arbitrum mainnet to the data feed, added more clarity for date/time headers
> adding arbitrum

- src/contexts/Graph.js
Moving from hosted service to studio network
> Updating Eth Main Graph to Studio

- src/components/TipTable.js
- src/contexts/Graph.js
- src/contexts/GraphAutopay.js
Symbol and chain Filters were not working for the Tip table, now they are populating and can be used in tandem
> fixed filters for Tip Table

- src/contexts/GraphAutopay.js
Adding Goerli Network's Autopay subgraph for  the TipTable
> adding goerli autopay

- src/contexts/Graph.js
new address required new subgraph version to be reflected in API key
> updatingmainnetaddress

- src/contexts/Graph.js
adding Optimism mainnet to the graph
> add op mainnet

- src/contexts/Graph.js
- src/contexts/GraphAutopay.js
- src/utils/queryDataParsers.js
adding sepolia network to the tip table
> sepoliatips

- src/utils/queryDataParsers.js
> pepedecimals

- src/utils/queryDataParsers.js
added conditions for coins that had more than 2 zeroes after the decimal, and cut off the ones that had infinite zeroes.
> crudcoin extension

- src/utils/helpers.js
> onetime bal

- src/components/TipTable.js
- src/contexts/GraphAutopay.js
resolving an extensible object issue for matic.
> objext patch

- src/contexts/GraphAutopay.js
Applying extensible object fix to all instances
> obj fix all

- src/contexts/Graph.js
applied same solution to Graph.js, originally just applied to GraphAutoPay.js
> feed graph obj ext

- src/components/Table.js
Added a search bar to the reporter filter
> reportersearch

- src/contexts/Graph.js
- src/utils/helpers.js
Added functionality to allow 2 uri queries to get applied to same chain during transition process to new oracle
> adding 2 uris

- src/components/AllFeeds.js
- src/components/AllTips.js
- src/components/Table.js
- src/components/TipTable.js
- src/styles/Table.css
adjusted columns for smaller window widths as well as retaining state during incoming new data
> column ui fix

- src/contexts/Graph.js
- src/contexts/GraphAutopay.js
migration of ethmain and sepolia subgraphs to arbitrum
> arbitrum migrate

- src/components/AllTips.js
- src/components/ErrorBoundary.js
- src/utils/helpers.js
adjusted try catch to be more general for tip table. as well as to prevent freezing on load as well.
> new try catch

- src/utils/helpers.js
- src/utils/queryDataParsers.js
Added formatting for StringQuery type
> stringquerytype

- src/components/Table.js
- src/utils/queryDataParsers.js
added date filter functionality for current set of data.
> first date filter push

- src/components/AllFeeds.js
- src/components/Table.js
addressed the initial load displaying all reports instead of initial 6 with load button
> longfeedfix

- src/contexts/Graph.js
adjusted link for polygonzkevm transactions
> fixed event link

- src/contexts/Graph.js
adding amoy testnet in place of mumbai
> adding amoy

- src/contexts/Graph.js
> adding zksync

- src/contexts/GraphAutopay.js
updated mumbai to amoy autopay contract to reflect on tip table
> chaning mumbai to amoy tips

- src/contexts/Graph.js
adding linea testnet for data feed
> adding linea testnet

- src/contexts/Graph.js
> adding optim sepolia

- src/contexts/Graph.js
- src/contexts/GraphAutopay.js
upgraded hosted service graphs to studio, graph is sunsetting hosted service on June 12th.
> move to studio graph

- src/contexts/Graph.js
- src/contexts/GraphAutopay.js
api links were being pulled that no longer were being serviced, namely the 'gateway' links
> removed gateway links

- package.json
- src/contexts/Graph.js
Adding scroll mainnet oracle to the data feed
> add scroll

- src/components/AllFeeds.js
- src/components/Table.js
- src/components/TipTable.js
- src/contexts/Graph.js
- src/contexts/GraphAutopay.js
- src/utils/apollo.js
- src/utils/helpers.js
- src/utils/queryDataParsers.js
Optimized loading of data to prevent load freezing
> fast load fix

- package.json
update package & package-lock to move react scripts to dependencies
> react-scripts fix

- package.json
- procfile
- server.js
> Filterretention

- package.json
- procfile
> Fix production deployment configuration

- src/utils/queryDataParsers.js
The issue is in the wsteth case structure. There's no return event statement after the USD condition, and it's falling through to the cult case.
> fixed wsteth feed on scroll
